server {
    listen 80;
    server_name www.petflow.com petflow.com;

    # React SPA build output
    root /var/www/petflow/frontend/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

